name: qr_attendance_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.7.0
  dartz: ^0.10.1
  
  # Networking
  dio: ^5.7.0
  
  # Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.2
  
  # QR Code
  mobile_scanner: ^5.2.3
  
  # Device Info
  network_info_plus: ^5.0.0
  device_info_plus: ^10.0.0
  
  # Utils
  intl: ^0.19.0
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
